apiVersion: v1
kind: Pod
metadata:
  name: nodejs-pod
spec:
  containers:
  - image: exercise1_11:latest
    name: frontend-example-docker
    ports:
    - containerPort: 5000
      hostPort: 5000
      protocol: TCP
