version: '3.5'
services:
  db_pg:
      image: postgres
      restart: always
      volumes:
        - ./database:/var/lib/postgresql/data
      ports:
        - 5432:5432
      environment:
        POSTGRES_PASSWORD: postgres
      container_name: db_pg
  adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
