FROM ubuntu:16.04 

ENV LC_ALL=C.UTF-8 
WORKDIR /app
RUN apt-get update && apt-get install -y wget
RUN apt-get install -y python curl 
COPY frontend-example-docker .
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash
RUN apt-get install -y nodejs 
EXPOSE 5000

ENV API_URL="http://localhost:8000 npm start"
RUN npm install webpack && \
    npm install && \
    useradd -m app && \
    chown -R app:app /app

USER app
 
WORKDIR /app 

ENTRYPOINT API_URL=http://localhost:8000 npm start
